title: Standardizing Service Mesh Value Measurement
email: community@layer5.io #this is also the email contact forms will go
description: "Service Mesh Performance (SMP): Measure your service mesh performance using SMP. SMP provides a universal performance index to gauge your mesh’s efficiency against deployments in other organizations’ environments."
baseurl: "" # the subpath of your site, e.g. /blog

author: Layer5 Authors
twitter_username: smp
github_username: l5io

twitter:
  card: summary
  username: smp
  url: "https://twitter.com/smp_spec"
  image: "https://smp-spec.io/assets/img/logo/smp.png"

# logo:
#   path:
# height: 80px #height in px, defaults to 52px

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-coffeescript

analytics:
  google: UA-152604689-2

collections_dir: collections
collections:
  blog:
    output: true
    permalink: /blog/:categories/:title
    future: true

markdown: kramdown
